babyguard/babyguard/food/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
import babyguard.food.views_food as views_food
import babyguard.food.views_eating as views_eating

urlpatterns = [
    url('add_food$', views_food.add_food, name='add_food'),
    url('get_food$', views_food.get_food, name='get_food'),
    url('del_food$', views_food.del_food, name='del_food'),
    url('update_food$', views_food.update_food, name='update_food'),
    url('reset_all_food$', views_food.reset_all_food, name='reset_all_food'),
    url('add_comment$', views_food.add_comment, name='add_comment'),

    url('add_eating$', views_eating.add_eating, name='add_eating'),
    url('get_eating$', views_eating.get_eating, name='get_eating'),
    url('del_eating$', views_eating.del_eating, name='del_eating'),
    url('update_eating$', views_eating.update_eating, name='update_eating'),
    url('reset_all_eating$', views_eating.reset_all_eating, name='reset_all_eating'),
]

babyguard/babyguard/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('babyguard.account.urls')),
    #url(r'^ask/', include('babyguard.ask.urls')),
    url(r'^audio/', include('babyguard.audio.urls')),
    url(r'^check/', include('babyguard.check.urls')),
    url(r'^chart/', include('babyguard.chart.urls')),
    #url(r'^course/', include('babyguard.course.urls')),
    url(r'^food/', include('babyguard.food.urls')),
    url(r'^auth/', include('babyguard.auth.urls')),
    #url(r'^video/', include('babyguard.video.urls')),
    url(r'^sns/', include('babyguard.sns.urls')),
    url(r'^lab/', include('babyguard.lab.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
print ('url.py34', '='*80, 'settings.STATIC_URL= ', settings.STATIC_URL,  'settings.STATIC_ROOT= ', settings.STATIC_ROOT)

babyguard/babyguard/food/models.py
# -*- coding: utf-8 -*-
from redisco import models

class CommentModel(models.Model):
    food_id = models.Attribute(required=True, unique = False)
    username = models.Attribute(required=True)
    comment = models.Attribute(required=True)
    created_at = models.DateTimeField(auto_now_add=True) 

class EatingModel(models.Model):
    eating_id = models.Attribute(required=True, unique = True)###id
    day = models.Attribute(required=False, default='')
    pics = models.Attribute(required=False, default='')###图片
    name = models.Attribute(required=False, default='')###名字
    kind = models.Attribute(required=False, default='')###类型（点心、正餐）
    created_at = models.DateTimeField(auto_now_add=True) 
    
class FoodModel(models.Model):
    food_id = models.Attribute(required=True, unique = True)###id
    day = models.Attribute(required=False, default = '',)###
    breakfast = models.Attribute(required=False, default='')###早餐
    lunch = models.Attribute(required=False, default='')###午餐
    dinner = models.Attribute(required=False, default='')###晚餐
    created_at = models.DateTimeField(auto_now_add=True) 
    

babyguard/babyguard/food/forms.py
#-*- coding: gb18030 -*-
from django import forms

class CommentForm(forms.Form):
    food_id = forms.CharField()
    username = forms.CharField()
    comment = forms.CharField()

class EatingForm(forms.Form):
    eating_id = forms.CharField()
    day = forms.CharField()
    pics = forms.CharField()
    name = forms.CharField()
    kind = forms.CharField()
    
class FoodForm(forms.Form):
    food_id = forms.CharField()
    day = forms.CharField()
    breakfast = forms.CharField()
    lunch = forms.CharField()
    dinner = forms.CharField()

babyguard/babyguard/food/templates/add_eating.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <script type="text/javascript" src="http://123.206.69.25/static/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="http://123.206.69.25/static/jquery.form.min.js"></script>
    <script type="text/javascript">  
        function preImg(sourceId, targetId) {  
            if (typeof FileReader === 'undefined') {  
                alert('Your browser does not support FileReader...');  
                return;  
            }  
            var reader = new FileReader();  
          
            reader.onload = function(e) {  
                var img = document.getElementById(targetId);  
                img.src = this.result;  
                img.width= 40;
                img.height=80;
            }  
            reader.readAsDataURL(document.getElementById(sourceId).files[0]);  
        }  
        $('input[name=FileContent]').change(function () {
            console.log('change');
        });
        function SendUrl2Server(){
            url = 'http://123.206.69.25:8000/food/add_eating'
            var options = { 
                        type: 'post',
                        url: url,
                        dataType: 'json',
                success:function(ret) { 
                    console.log('ret= '+ret);
                },
                error:function (ret) {
                    alert(ret.responseText);
                }
            }; 
             
            // pass options to ajaxForm 
            $('#uploadForm').ajaxSubmit(options);
        }
        function UploadPicture(url) {
            var options = { 
                        type: 'post',
                        url: url,
                        dataType: 'json',
                success:function(ret) { 
                    console.log('ret= '+ret);

                    $('#id_pics').html(ret.data.download_url);
                    SendUrl2Server();

                    //$('#fileid').text(ret.data.fileid);
                    //$('#url').text(ret.data.url);
                    //$('#downloadRet').show();
                },
                error:function (ret) {
                    alert(ret.responseText);
                }
            }; 
             
            // pass options to ajaxForm 
            //这里的意思是：把previewForm发送到url指定的地址上去
            $('#previewForm').ajaxSubmit(options);
        }
        function SendPictureFirst () {
            // 请将以下获取签名的链接换成您部署好的服务端http url
            // 建议通过业务登陆态检查来增强安全性，避免签名被非法获取
            $.getJSON('http://123.206.69.25:8000/auth/auth_pic?type=upload', function(data) {
                var sign = data.sign,
                    url = data.url + '?sign=' + encodeURIComponent(sign);
                console.log('url='+url);    
                UploadPicture(url);
            });
        }
    </script>  

    <title>Add Eating</title>
</head>
<body>
    <h1>Eating</h1>

    <form action="" id="previewForm">  
        <input type="file" name="FileContent" id="imgOne" onchange="preImg(this.id,'imgPre');" />  
        <img id="imgPre" src="" style="display: block;" />    
    </form>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="add_eating" method="post" id="uploadForm">
       <label for="id_eating_id">Eating id:</label></th><td><input id="id_eating_id" name="eating_id" type="text" value="1" />
       <br>
       <label for="id_day">Day:</label></th><td><input id="id_day" name="day" type="text" />
       <label for="id_pics">Pics:</label></th><td><input id="id_pics" name="pics" type="text" value="1" />
       <label for="id_name">Name:</label></th><td><input id="id_name" name="name" type="text" value="2" />
       <label for="id_kind">Kind:</label></th><td><input id="id_kind" name="kind" type="text" value="3" />
       <!--input type="submit" value="Add"-->
       <input id="subbtn" type="button" value="SendWithPicture" onclick="SendPictureFirst();">
    </form>

    <form action="update_eating" method="post">
       <label for="id_eating_id">Eating id:</label></th><td><input id="id_eating_id" name="eating_id" type="text" value="1" /><br>
       <label for="id_day">Day:</label></th><td><input id="id_day" name="day" type="text" />
       <label for="id_pics">Pics:</label></th><td><input id="id_pics" name="pics" type="text" value="1" />
       <label for="id_name">Name:</label></th><td><input id="id_name" name="name" type="text" value="2" />
       <label for="id_kind">Kind:</label></th><td><input id="id_kind" name="kind" type="text" value="3" />
       <input type="submit" value="Update">
    </form>

    <table>  
    {% for food in food_list%}
        <tr>
            <td><lable for='id_order_no'>id:</lable></td><td>{{ food.food_id}}</td>
            <td><lable for='id_custome_no'>breakfast:</lable></td><td>{{ food.breakfast}}</td>
            <td><lable for='id_custome_no'>lunch:</lable></td><td>{{ food.lunch}}</td>
            <td><lable for='id_custome_no'>dinner:</lable></td><td>{{ food.dinner}}</td>
        </tr>  
    {% endfor %}
    </table>  
</body>
</html>

babyguard/babyguard/food/templates/add_food.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>Add Food</title>
</head>
<body>
    <h1>Food</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="add_food" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Add">
    </form>

    <form action="update_food" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Update">
    </form>

    <table>  
    {% for food in food_list%}
        <tr>
            <td><lable for='id_order_no'>id:</lable></td><td>{{ food.food_id}}</td>
            <td><lable for='id_custome_no'>breakfast:</lable></td><td>{{ food.breakfast}}</td>
            <td><lable for='id_custome_no'>lunch:</lable></td><td>{{ food.lunch}}</td>
            <td><lable for='id_custome_no'>dinner:</lable></td><td>{{ food.dinner}}</td>
        </tr>  
    {% endfor %}
    </table>  
</body>
</html>

babyguard/babyguard/food/templates/comment_eating.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>Add Eating</title>
</head>
<body>
    <h1>Eating</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Comment">
    </form>

</body>
</html>

babyguard/babyguard/food/templates/comment_food.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>Add Food</title>
</head>
<body>
    <h1>Task</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Comment">
    </form>

</body>
</html>